---
- hosts: practice
  become_user: root
  remote_user: ansible
  become: true
  tasks:
    - name: user creation
      user:
        name: papu
        state: present
    - name: Package installation
      yum:
        name: docker*
        state: latest
    - name: service started
      service:
        name: docker
        state: started
        enabled: yes
    - name: Pulling docker images
      docker_image:
        name: nginx:latest
        state: pull
    - name: Starting nginx container
      docker_container:
        name: Nginx_Container
        image: nginx:latest
