---
- hosts: practice
  become_user: root
  remote_user: ansible
  become: true
  tasks:
    - name: user creation
      user:
        name: papu
        state: present
    - name: Package installation
      yum:
        name: docker*
        state: latest
